# Generated by Django 3.0.5 on 2021-02-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('tipo_pregunta', models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'Fill In The Blank'), (3, 'True Or Flase'), (4, 'Short Answer')], default=4)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.Deck')),
            ],
        ),
    ]
